railstutorial: "https://www.railstutorial.org/"
learnenough:  "https://www.learnenough.com/"
railsbook: "https://www.railstutorial.org/book"
videoseries: "https://screencasts.railstutorial.org/"
contact_here: "https://www.railstutorial.org/contact"
help_here: "https://www.railstutorial.org/help"
